"""Export pipeline outputs to an Overleaf-ready folder.

- outputs/tables/*.csv        -> outputs/overleaf/tables/<name>.tex   (booktabs, \\input-ready)
- outputs/figures/*.pdf|*.png -> outputs/overleaf/figures/            (copied)
- outputs/numbers.json        -> outputs/overleaf/numbers.tex         (\\newcommand per number)

Nothing here invents a value: if an input does not exist, the corresponding output is not
written and the function reports it. Numbers are formatted with a thin-space thousands
separator and a fixed number of decimals given in numbers.json as {"name": {"value": x,
"decimals": n}} or simply {"name": x}.
"""
from __future__ import annotations

import csv
import json
import re
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
OUT = ROOT / "outputs"
OVERLEAF = OUT / "overleaf"

_LATEX_SPECIALS = {"&": r"\&", "%": r"\%", "$": r"\$", "#": r"\#", "_": r"\_", "{": r"\{",
                   "}": r"\}", "~": r"\textasciitilde{}", "^": r"\textasciicircum{}"}


def latex_escape(s: str) -> str:
    return "".join(_LATEX_SPECIALS.get(ch, ch) for ch in str(s))


def csv_to_booktabs(csv_path: Path, caption: str | None = None, label: str | None = None) -> str:
    """Convert a CSV (header + rows) to a booktabs tabular. Numeric columns are right-aligned."""
    with csv_path.open(newline="", encoding="utf-8") as f:
        rows = list(csv.reader(f))
    if not rows:
        raise ValueError(f"{csv_path} is empty")
    header, body = rows[0], rows[1:]

    def is_num(v: str) -> bool:
        return bool(re.fullmatch(r"-?\d+(\.\d+)?", v.strip()))

    align = "".join("r" if body and all(is_num(r[i]) for r in body if i < len(r) and r[i] != "")
                    else "l" for i in range(len(header)))
    lines = [r"\begin{table}[htbp]", r"\centering"]
    if caption:
        lines.append(rf"\caption{{{latex_escape(caption)}}}")
    if label:
        lines.append(rf"\label{{{label}}}")
    lines += [rf"\begin{{tabular}}{{{align}}}", r"\toprule",
              " & ".join(latex_escape(h) for h in header) + r" \\", r"\midrule"]
    for r in body:
        lines.append(" & ".join(latex_escape(v) for v in r) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    return "\n".join(lines)


def format_number(value, decimals: int | None = None) -> str:
    if isinstance(value, str):
        return latex_escape(value)
    if decimals is None:
        decimals = 0 if float(value).is_integer() else 2
    s = f"{value:,.{decimals}f}"
    return s.replace(",", r"\,")  # thin space as thousands separator


def numbers_to_tex(numbers: dict) -> str:
    """Build \\newcommand lines. Macro names must be letters only (LaTeX rule)."""
    out = ["% generated by scripts/90_export_overleaf.py; do not edit by hand", ""]
    for name, spec in numbers.items():
        if not re.fullmatch(r"[A-Za-z]+", name):
            raise ValueError(f"macro name must be letters only: {name}")
        if isinstance(spec, dict):
            value, decimals = spec["value"], spec.get("decimals")
        else:
            value, decimals = spec, None
        out.append(rf"\newcommand{{\{name}}}{{{format_number(value, decimals)}}}")
    return "\n".join(out) + "\n"


def export_all() -> dict:
    report = {"tables": [], "figures": [], "numbers": None, "skipped": []}
    (OVERLEAF / "tables").mkdir(parents=True, exist_ok=True)
    (OVERLEAF / "figures").mkdir(parents=True, exist_ok=True)

    tables_dir = OUT / "tables"
    for csv_path in sorted(tables_dir.glob("*.csv")):
        tex = OVERLEAF / "tables" / (csv_path.stem + ".tex")
        tex.write_text(csv_to_booktabs(csv_path, label=f"tab:{csv_path.stem}"), encoding="utf-8")
        report["tables"].append(tex.name)

    for fig in sorted((OUT / "figures").glob("*")):
        if fig.suffix.lower() in (".pdf", ".png"):
            shutil.copy2(fig, OVERLEAF / "figures" / fig.name)
            report["figures"].append(fig.name)

    numbers_path = OUT / "numbers.json"
    if numbers_path.exists():
        numbers = json.loads(numbers_path.read_text(encoding="utf-8"))
        (OVERLEAF / "numbers.tex").write_text(numbers_to_tex(numbers), encoding="utf-8")
        report["numbers"] = len(numbers)
    else:
        report["skipped"].append("outputs/numbers.json not found: numbers.tex not written")
    return report
